language: c

services:
  - docker

compiler:
  - clang
  - gcc

before_install:
  - docker pull abranhe/clib
  - docker run -it -v $(pwd):/src -w /src test sh -c "clib install"

script: docker run -it -v $(pwd):/src -w /src test sh -c "make run-test"

notifications:
  email: false