language: c

services:
  - docker

compiler:
  - clang
  - gcc

before_install:
  - docker pull abranhe/clib
  - echo  "$(pwd)"
  - docker run --rm -v "$(pwd)":/app -w /app abranhe/clib install

script: make run-test

notifications:
  email: false
