language: c

services:
  - docker

compiler:
  - clang
  - gcc

before_install:
  - docker pull abranhe/clib
  - docker run -it -v "$(pwd)":/opener abranhe/clib bash && ls -alt

script: make run-test

notifications:
  email: false
