language: c

services:
  - docker

compiler:
  - clang
  - gcc

before_install:
  - docker pull abranhe/clib
  - docker run -it -v $(pwd):/src -w /src abranhe/clib sh -c "ls"

script: echo Hello
# docker run -it -v $(pwd):/src -w /src ubuntu "make run-test"

notifications:
  email: false