language: c

services:
  - docker

compiler:
  - clang
  - gcc

before_install:
  - docker pull abranhe/clib
  - docker run -it -v $(pwd):/src abranhe/clib  && ls -alt

script: echo hello
# script: make run-test

notifications:
  email: false
