language: c

services:
  - docker

compiler:
  - clang
  - gcc

before_install:
  - docker pull abranhe/clib
  - docker run -it --rm -v $(pwd):/src -w /src  abranhe/clib

script: pwd && ls -alt 
# script: make run-test

notifications:
  email: false
